# Generated by Django 5.0.6 on 2024-06-19 02:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "ACTIVE"), (1, "INACTIVE")],
                        db_index=True,
                        default=0,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "PENDING"), (1, "ACCEPTED"), (2, "REJECTED")],
                        default=0,
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_requests",
                        to="users.userprofile",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_requests",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserFollower",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "ACTIVE"), (1, "INACTIVE")],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("followed_date", models.DateTimeField(auto_now_add=True)),
                ("unfollowed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "FOLLOWING"),
                            (1, "UN_FOLLOWED"),
                            (2, "BLOCKED"),
                            (3, "RESTRICTED"),
                        ],
                        default=0,
                    ),
                ),
                ("is_close_friend", models.BooleanField(default=False)),
                (
                    "followed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed_by",
                        to="users.userprofile",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
